FROM ubuntu:xenial

RUN apt-get update -y
RUN apt-get install -y make gcc autoconf cmake g++ openjdk-8-jdk libtool ocaml python2.7
RUN apt-get install -y mercurial wget
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
