FROM ubuntu:xenial

RUN apt-get update -y
RUN apt-get install -y \
    autoconf ccache cmake cpio g++ gcc git libtool make \
    ocaml openjdk-8-jdk python2.7 unzip wget zip

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
