#!groovy
/**
 * Jenkins pipeline to build Corda on MS Windows server
 */

/**
 * Kill already started job.
 * Assume new commit takes precendence and results from previous
 * unfinished builds are not required.
 * This feature doesn't play well with disableConcurrentBuilds() option
 */
@Library('corda-shared-build-pipeline-steps')
import static com.r3.build.BuildControl.killAllExistingBuildsForJob

killAllExistingBuildsForJob(env.JOB_NAME, env.BUILD_NUMBER.toInteger())

pipeline {
    agent { label 'mswin' }
    options {
        ansiColor('xterm')
        timestamps()
        timeout(time: 4, unit: 'HOURS')
    }

    triggers {
      pollSCM ignorePostCommitHooks: true, scmpoll_spec: '@midnight'
    }

    stages {
        stage('Unit Tests') {
            steps {
                sh "./gradlew --no-daemon " +
                        "--stacktrace " +
                        "-Pcompilation.warningsAsErrors=false " +
                        "-Ptests.failFast=true " +
                        "clean test"
            }
        }

        stage('Integration Tests') {
            steps {
                sh "./gradlew --no-daemon " +
                        "integrationTest"
            }
        }
    }

    post {
        always {
            archiveArtifacts allowEmptyArchive: true, artifacts: '**/logs/**/*.log'
            junit testResults: '**/build/test-results/**/*.xml', allowEmptyResults: true
        }
        cleanup {
            deleteDir() /* clean up our workspace */
        }
    }
}
