@Library('corda-shared-build-pipeline-steps@5.1') _

forwardMerger(
    targetBranch: 'release/os/4.10',
    originBranch: 'release/os/4.9',
    slackChannel: '#build-team-automated-notifications'
)

