#!/usr/bin/env bash

NUM_CPU=$(nproc)

if ((NUM_CPU <= 8)); then
  export CORDA_CORE_TESTING_FORKS=1
  export CORDA_NODE_INT_TESTING_FORKS=1
  export CORDA_NODE_TESTING_FORKS=1
  export CORDA_INT_TESTING_FORKS=1
  export CORDA_TESTING_FORKS=1

elif ((NUM_CPU > 8)); then
  export CORDA_CORE_TESTING_FORKS=2
  export CORDA_NODE_INT_TESTING_FORKS=2
  export CORDA_NODE_TESTING_FORKS=2
  export CORDA_INT_TESTING_FORKS=2
  export CORDA_TESTING_FORKS=2

elif ((NUM_CPU > 16)); then
  export CORDA_CORE_TESTING_FORKS=4
  export CORDA_NODE_INT_TESTING_FORKS=4
  export CORDA_NODE_TESTING_FORKS=4
  export CORDA_INT_TESTING_FORKS=2
  export CORDA_TESTING_FORKS=2

else ((NUM_CPU > 32))
  export CORDA_CORE_TESTING_FORKS=8
  export CORDA_NODE_INT_TESTING_FORKS=8
  export CORDA_NODE_TESTING_FORKS=8
  export CORDA_INT_TESTING_FORKS=4
  export CORDA_TESTING_FORKS=4
fi

