package net.corda.example

class ContainsAutoGeneratedClass {
    private open class PrivateInnerClass

    private inline fun runSomething(crossinline action: PrivateInnerClass.() -> Unit): PrivateInnerClass {
        return object: PrivateInnerClass() {
            fun run() = action()
        }
    }

    private val timer = PrivateInnerClass()

    fun methodContainingInlinedFunction() {
        runSomething {
            println()
        }
    }
}