import static com.r3.build.BuildControl.killAllExistingBuildsForJob
@Library('existing-build-control')
import static com.r3.build.BuildControl.killAllExistingBuildsForJob

killAllExistingBuildsForJob(env.JOB_NAME, env.BUILD_NUMBER.toInteger())

pipeline {
    agent { label 'k8s' }
    options { timestamps() }

    environment {
        DOCKER_TAG_TO_USE = "${UUID.randomUUID().toString().toLowerCase().subSequence(0, 12)}"
        EXECUTOR_NUMBER = "${env.EXECUTOR_NUMBER}"
        BUILD_ID = "${env.BUILD_ID}-${env.JOB_NAME}"
    }

    stages {
        stage('Unit Tests') {
            steps {

                script {
                    pullRequest.createStatus(status: 'pending',
                            context: 'continuous-integration/jenkins/pr-merge/unitTest',
                            description: 'Unit Tests Building',
                            targetUrl: "${env.JOB_URL}/testResults")
                }

                withCredentials([string(credentialsId: 'container_reg_passwd', variable: 'DOCKER_PUSH_PWD')]) {
                    sh "./gradlew " +
                            "-DbuildId=\"\${BUILD_ID}\" " +
                            "-Dkubenetize=true " +
                            "-Ddocker.push.password=\"\${DOCKER_PUSH_PWD}\" " +
                            "-Ddocker.work.dir=\"/tmp/\${EXECUTOR_NUMBER}\" " +
                            "-Ddocker.provided.tag=\"\${DOCKER_TAG_TO_USE}\"" +
                            " allParallelUnitTest"
                }
                sh "echo hello"
            }
        }
    }

    post {

        always {
            junit testResults: '**/build/test-results-xml/**/*.xml', allowEmptyResults: true
        }

        success {
            script {
                pullRequest.createStatus(status: 'success',
                        context: 'continuous-integration/jenkins/pr-merge/unitTest',
                        description: 'Unit Tests Passed',
                        targetUrl: "${env.JOB_URL}testResults")
            }
        }

        failure {
            script {
                pullRequest.createStatus(status: 'failure',
                        context: 'continuous-integration/jenkins/pr-merge/unitTest',
                        description: 'Unit Tests Failed',
                        targetUrl: "${env.JOB_URL}testResults")
            }
        }

        cleanup {
            deleteDir() /* clean up our workspace */
        }
    }
}