#!/usr/bin/env bash

file="${BASH_SOURCE[0]}"
linked_file="$(test -L "$file" && readlink "$file" || echo "$file")"
base_dir="$(cd "$(dirname "$linked_file")/../" && pwd)"
version="$(cat $base_dir/../build.gradle | sed -n 's/^[ ]*ext\.corda_release_version[ =]*"\([^"]*\)".*$/\1/p')"
jar_file="$base_dir/build/libs/corda-djvm-$version-all.jar"

CLASSPATH=${CLASSPATH:-}

DEBUG=`echo "${DEBUG:-0}" | sed 's/^[Nn][Oo]*$/0/g'`
DEBUG_PORT=5005
DEBUG_AGENT=""

if [ "$DEBUG" != 0 ]; then
    echo "Opening remote debugging session on port $DEBUG_PORT"
    DEBUG_AGENT="-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=$DEBUG_PORT"
fi

java $DEBUG_AGENT -cp "$CLASSPATH:.:tmp:$jar_file" net.corda.sandbox.tools.cli.Program "$@"
