#!/usr/bin/env bash

file="${BASH_SOURCE[0]}"
base_dir="$(cd "$(dirname "$file")/" && pwd)"
version="$(cat $base_dir/../../build.gradle | sed -n 's/^[ ]*ext\.corda_release_version[ =]*"\([^"]*\)".*$/\1/p')"

# Build DJVM JAR
cd "$base_dir/.."
../gradlew shadowJar

# Create a symbolic link to the `djvm` utility
ln -sf "$base_dir/djvm" /usr/local/bin/djvm

# Generate auto-completion file for Bash and ZSH
cd "$base_dir"
java -cp "$base_dir/../build/libs/corda-djvm-$version-all.jar" picocli.AutoComplete \
    -n djvm net.corda.djvm.tools.cli.Commands -f
