#!/usr/bin/env bash
# Will attempt to execute a corda node within all subdirectories in the current working directory.

set -euo pipefail
export CAPSULE_CACHE_DIR=cache

# Allow the script to be run from outside the nodes directory.
basedir=$( dirname "$0" )
cd "$basedir"

if which osascript >/dev/null; then
    # MacOS X: open each node in a in new tab.
    first=true
    script='tell app "Terminal"
    activate'
    rootdir=`pwd`
    for dir in `ls`; do
        if [ -d $dir ]; then
            cmd="bash -c 'cd $rootdir/$dir; exec ./NODEJAR_NAME && exit'"
            script="$script
    tell application \"System Events\" to tell process \"Terminal\" to keystroke \"t\" using command down
    delay 0.5
    do script \"$cmd\" in window 1"
            first=false
        fi
    done

    # Now do the web servers.
    if [[ "${NO_WEB_SERVER:-}" == "" ]]; then
        for dir in `ls`; do
            if [ -d $dir ]; then
                cmd="bash -c 'cd $rootdir/$dir; /usr/libexec/java_home -v 1.8 --exec java -jar WEBJAR_NAME && exit'"
                script="$script
        tell application \"System Events\" to tell process \"Terminal\" to keystroke \"t\" using command down
        delay 0.5
        do script \"$cmd\" in window 1"
                first=false
            fi
        done
    fi
    script="$script
end tell"
    osascript -e "$script"
else
    # Some other UNIX, probably Linux (does not support msys or cygwin)
    # TODO: msys and cygwin support
    #
    # If it is set, it means that java overrides the default system java, which is what we want.
    if [ -n "${JAVA_HOME-}" ]; then
	export PATH="$JAVA_HOME/bin:$PATH"
    fi
    for dir in `ls`; do
        if [ -d $dir ]; then
            pushd $dir >/dev/null
            xterm -T "`basename $dir`" -e './NODEJAR_NAME' &
            if [[ "${NO_WEB_SERVER:-}" == "" ]]; then
                xterm -T "`basename $dir` Web Server" -e 'java -jar WEBJAR_NAME' &
            fi
            popd >/dev/null
        fi
    done
fi
