#!/bin/bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# make the sx tool available for the user
alias sx="bash ${DIR}/tools/sx/sx"

# load sx configuration
if [ -e "/tmp" ]; then
    TMPDIR=${TMPDIR:-/tmp}
fi
TMP_CONFIG="${TMPDIR}/sx.config"
if [ -z "${TMPDIR}" ]; then
    TMP_CONFIG=$(tempfile)
fi

sx shell auto-completion > "${TMP_CONFIG}"
source "${TMP_CONFIG}"
