package net.corda.attestation.host.sgx.bridge.wrapper

/**
 * An opaque type used to hold enclave launch information. Used by
 * sgx_create_enclave to initialize an enclave. The license is generated by the
 * launch enclave.
 */
typealias LaunchToken = ByteArray

/**
 * Create a new launch token.
 */
fun newLaunchToken(): LaunchToken = ByteArray(1024)
