DROP SCHEMA IF EXISTS "${schema}" CASCADE;
DROP OWNED by "${schema}";
DROP USER IF EXISTS "${schema}";
CREATE USER "${schema}" WITH LOGIN password '1234';
CREATE SCHEMA "${schema}";
GRANT USAGE, CREATE ON SCHEMA "${schema}" TO "${schema}";
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON ALL tables IN SCHEMA "${schema}" TO "${schema}";
ALTER DEFAULT privileges IN SCHEMA "${schema}" GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON tables TO "${schema}";
GRANT USAGE, SELECT ON ALL sequences IN SCHEMA "${schema}" TO "${schema}";
ALTER DEFAULT privileges IN SCHEMA "${schema}" GRANT USAGE, SELECT ON sequences TO "${schema}";