package net.corda.bootstrapper

import net.corda.testing.CliBackwardsCompatibleTest

class NetworkBootstrapperBackwardsCompatibilityTest : CliBackwardsCompatibleTest(NetworkBootstrapperRunner::class.java)