DROP USER ${schema} CASCADE
CREATE USER ${schema} IDENTIFIED BY 1234
GRANT UNLIMITED TABLESPACE TO ${schema}
GRANT CREATE SESSION TO ${schema}
GRANT CREATE TABLE TO ${schema}
GRANT CREATE SEQUENCE TO ${schema}